<a href="https://colab.research.google.com/github/DanielBrisch/Heartdiseases/blob/03/3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [ ]:
!pip install ucimlrepo
from ucimlrepo import fetch_ucirepo
doenca_cardiaca = fetch_ucirepo(id=45)

In [ ]:
X = doenca_cardiaca.data.features
X = X[['age', 'chol', 'cp']]

In [ ]:
target = doenca_cardiaca.data.targets
target = (target > 0) * 1

In [ ]:
df_cp = pd.get_dummies(X['cp'], prefix='cp')
X = X.drop('cp', axis=1).join(df_cp)

In [ ]:
y = tf.constant(target, dtype=tf.float32)

In [ ]:
X.head()

age  chol  cp_1  cp_2  cp_3  cp_4
0   63   233     1     0     0     0
1   67   286     0     0     0     1
2   67   229     0     0     0     1
3   37   250     0     0     1     0
4   41   204     0     1     0     0

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
X[['age', 'chol']] = scaler.fit_transform(X[['age', 'chol']])

print('primeiros valores normalizados de age:', X['age'].head())
print('primeiros valores normalizados de chol: ', X['chol'].head())

primeiros valores normalizados de age: 0    0.948726
1    1.392002
2    1.392002
3   -1.932564
4   -1.489288
Name: age, dtype: float64
primeiros valores normalizados de chol:  0   -0.264900
1    0.760415
2   -0.342283
3    0.063974
4   -0.825922
Name: chol, dtype: float64


In [ ]:
X.shape[1]

6

In [ ]:
tf.random.set_seed(31)

In [ ]:
quantidade_features = X.shape[1]
peso = tf.Variable(tf.random.normal([quantidade_features, 1]), name='peso')
vies = tf.Variable(tf.random.normal([1]), name='vies')

In [ ]:
def neuronio(x):
  z = tf.add(tf.matmul(x, peso), vies)
  return z

In [ ]:
vies.numpy(), peso.numpy()

(array([0.15100643], dtype=float32),
 array([[-0.3594139 ],
        [ 0.18532915],
        [ 2.3871737 ],
        [ 0.9996345 ],
        [ 0.09981808],
        [-0.06186233]], dtype=float32))

In [ ]:
X.iloc[0].values

array([ 0.94872647, -0.2649003 ,  1.        ,  0.        ,  0.        ,
        0.        ])

In [ ]:
neuronio(tf.constant([[0.94872647, -0.2649003, 1.0, 0.0, 0.0, 0.0]]))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[2.1481009]], dtype=float32)>

In [ ]:
pb = tf.sigmoid(neuronio(tf.constant([[0.94872647, -0.2649003, 1.0, 0.0, 0.0, 0.0]])))
pb

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.8954912]], dtype=float32)>

In [ ]:
entrada = tf.constant(X, dtype=tf.float32)
pb = tf.sigmoid(neuronio(entrada))
pb[:10].numpy()

array([[0.8954912 ],
       [0.43284974],
       [0.38352907],
       [0.7225751 ],
       [0.82242215],
       [0.7407992 ],
       [0.46614692],
       [0.5919096 ],
       [0.44382718],
       [0.4974511 ]], dtype=float32)

In [ ]:
calc_perda = tf.keras.losses.BinaryCrossentropy()

In [ ]:
perda = calc_perda(y_true = y, y_pred = pb)
perda.numpy()

0.9295621

In [ ]:
np.mean(y.numpy() == ((pb.numpy() > 0.5) * 1))

0.3696369636963696